"use client";
import Image from "next/image";
import { GripVertical, ImagePlus, Trash2 } from "lucide-react";
import { useEffect, useState } from "react";
import { IMAGE_TYPES, MAX_IMAGE_BYTES, MAX_VIDEO_BYTES, VIDEO_TYPES } from "@/lib/community/constants";
import { PsfitLoader } from "@/components/ui/psfit-loader";
type Preview={file:File;url:string};
export function MediaUploader(){
 const [items,setItems]=useState<Preview[]>([]);const [error,setError]=useState("");const [preparing,setPreparing]=useState(false);
 useEffect(()=>()=>items.forEach(i=>URL.revokeObjectURL(i.url)),[items]);
 async function choose(files:FileList|null){if(!files)return;setPreparing(true);try{const next=[...files];if(items.length+next.length>10){setError("Choose up to 10 images.");return}const invalid=next.find(file=>{const image=IMAGE_TYPES.includes(file.type as (typeof IMAGE_TYPES)[number]);const video=VIDEO_TYPES.includes(file.type as (typeof VIDEO_TYPES)[number]);return (!image&&!video)||(image&&file.size>MAX_IMAGE_BYTES)||(video&&file.size>MAX_VIDEO_BYTES)});if(invalid){setError("A selected file has an unsupported type or size.");return}if(next.some(f=>f.type.startsWith("video/"))&&(items.length||next.length>1)){setError("A video must be the only media item.");return}const video=next.find(f=>f.type.startsWith("video/"));if(video&&(await videoDuration(video))>60){setError("Post videos must be 60 seconds or shorter.");return}setError("");setItems(old=>[...old,...next.map(file=>({file,url:URL.createObjectURL(file)}))])}finally{setPreparing(false)}}
 return <div><label className="flex cursor-pointer items-center justify-center gap-2 rounded-2xl border border-dashed border-white/15 bg-white/[.025] p-8 text-sm text-muted hover:border-acid/50 hover:text-paper"><ImagePlus/><span>Add photos or a short video</span><input className="sr-only" type="file" name="media" accept="image/jpeg,image/png,image/webp,video/mp4,video/webm" multiple onChange={e=>void choose(e.target.files)}/></label>{preparing&&<div className="mt-3"><PsfitLoader size="sm" label="Preparing media..."/></div>}{error&&<p className="mt-2 text-sm text-red-400">{error}</p>}<div className="mt-3 grid grid-cols-2 gap-3 sm:grid-cols-3">{items.map((item,index)=><div key={item.url} className="relative aspect-square overflow-hidden rounded-xl bg-black">{item.file.type.startsWith("image/")?<Image unoptimized fill className="object-cover" src={item.url} alt="Upload preview"/>:<video className="h-full w-full object-cover" src={item.url}/>}<GripVertical className="absolute left-2 top-2 drop-shadow" size={18}/><button type="button" onClick={()=>setItems(old=>old.filter(x=>x!==item))} className="absolute right-2 top-2 rounded-full bg-black/70 p-2"><Trash2 size={15}/></button><input name={`alt_${index}`} aria-label={`Alternative description for media ${index+1}`} placeholder="Alt text" className="absolute inset-x-2 bottom-2 rounded-lg bg-black/70 px-2 py-1 text-xs"/></div>)}</div></div>;
}
function videoDuration(file:File){return new Promise<number>((resolve,reject)=>{const video=document.createElement("video");const url=URL.createObjectURL(file);video.preload="metadata";video.onloadedmetadata=()=>{URL.revokeObjectURL(url);resolve(video.duration)};video.onerror=()=>{URL.revokeObjectURL(url);reject(new Error("Video metadata could not be read."))};video.src=url})}
