"use client";
import { followUser,toggleLike } from "@/app/community/actions";
import type { CommunityPost } from "@/types/database";
import { BadgeCheck,MapPin } from "lucide-react";
import Link from "next/link";
import { useState } from "react";
import { PostCarousel } from "./post-carousel";
import { PostActionBar } from "./post-action-bar";
import { WorkoutBottomSheet } from "./workout-bottom-sheet";
import { PostMenu } from "./post-menu";
import { PostMusicCard } from "./post-music-card";
import { UserAvatar } from "./user-avatar";
export function MobilePostCard({post,viewerId,showFollow=false,onDeleted}:{post:CommunityPost;viewerId?:string;showFollow?:boolean;onDeleted?:()=>void}){const [workout,setWorkout]=useState(false);const [liked,setLiked]=useState(Boolean(post.liked));const [follow,setFollow]=useState<"idle"|"pending"|"accepted">("idle");const author=post.author;const hours=Math.max(1,Math.round((Date.now()-new Date(post.created_at).getTime())/3600000));async function doubleLike(){if(liked)return;setLiked(true);try{await toggleLike(post.id)}catch{setLiked(false)}}async function followAuthor(){setFollow("pending");try{setFollow(await followUser(post.user_id) as "pending"|"accepted")}catch{setFollow("idle")}}return <article className="mb-2 overflow-hidden border-y border-white/[.06] bg-[#040604] md:hidden"><header className="flex items-center gap-3 px-3 py-3"><Link href={`/u/${author?.username}`}><UserAvatar src={author?.avatar_url} name={author?.full_name} username={author?.username}/></Link><div className="min-w-0 flex-1"><div className="flex items-center gap-1.5"><Link href={`/u/${author?.username}`} className="truncate text-sm font-semibold">{author?.full_name??"PSFIT athlete"}</Link>{post.is_verified_workout&&<BadgeCheck size={14} className="shrink-0 text-acid"/>}</div><p className="flex items-center gap-1 truncate text-[11px] text-muted">@{author?.username??"athlete"} · {hours}h{post.location&&<><MapPin size={10}/> {post.location}</>}</p></div>{showFollow&&viewerId!==post.user_id&&<button onClick={followAuthor} disabled={follow!=="idle"} className="rounded-full border border-acid/30 px-3 py-1.5 text-[11px] font-semibold text-acid disabled:border-white/10 disabled:text-muted">{follow==="idle"?"Follow":follow==="pending"?"Requested":"Following"}</button>}<PostMenu own={viewerId===post.user_id} postId={post.id} onDeleted={onDeleted}/></header>{(post.media?.length||post.workout_receipt)&&<PostCarousel items={post.media??[]} receipt={post.workout_receipt} visualStyle={post.training_visual_style} includeReceipt={Boolean(post.is_verified_workout)} onDoubleTap={doubleLike}/>} {post.caption&&<p className="px-4 pb-3 pt-3 text-sm leading-5"><Link href={`/u/${author?.username}`} className="mr-1.5 font-semibold">@{author?.username}</Link>{post.caption}</p>}{post.music&&<div className="mx-3 mb-3"><PostMusicCard music={post.music}/></div>}<PostActionBar postId={post.id} liked={liked} saved={Boolean(post.saved)} likes={post.like_count+(liked&&!post.liked?1:0)} comments={post.comment_count} hasWorkout={Boolean(post.workout_receipt)} onWorkout={()=>setWorkout(true)}/>{post.is_verified_workout&&<p className="mx-4 mb-4 flex items-center gap-1 text-[10px] font-semibold uppercase tracking-wider text-aqua"><BadgeCheck size={12}/>Verified PSFIT Session</p>}{post.workout_receipt&&<WorkoutBottomSheet open={workout} onClose={()=>setWorkout(false)} receipt={post.workout_receipt} postId={post.id}/>}</article>}
