"use client";

import { followUser } from "@/app/community/actions";
import { ProfileSong } from "@/components/music/profile-song";
import type { CommunityProfile } from "@/types/database";
import { MapPin, MoreHorizontal } from "lucide-react";
import { useState } from "react";
import { FollowButton } from "./follow-button";
import { UserAvatar } from "./user-avatar";

export function ProfileHeader({profile,own}:{profile:CommunityProfile;own:boolean}){const [status,setStatus]=useState<"idle"|"pending"|"accepted">("idle");async function follow(){setStatus("pending");try{const next=await followUser(profile.id);setStatus(next as "pending"|"accepted")}catch{setStatus("idle")}}return <header className="border-b border-white/[.07] p-5 sm:p-7"><div className="flex gap-5"><UserAvatar src={profile.avatar_url} name={profile.full_name} username={profile.username} size="xl"/><div className="min-w-0 flex-1"><div className="flex items-start justify-between"><div><h1 className="text-2xl font-semibold">{profile.full_name??"PSFIT athlete"}</h1><p className="text-sm text-muted">@{profile.username}{profile.pronouns?` · ${profile.pronouns}`:""}</p><p className="mt-1 text-xs capitalize text-acid">{profile.profile_category?.replaceAll("_"," ")}</p></div><button className="text-muted"><MoreHorizontal/></button></div><div className="mt-4 flex gap-5 text-sm"><span><b>{profile.posts_count}</b> posts</span><span><b>{profile.followers_count}</b> followers</span><span><b>{profile.following_count}</b> following</span></div></div></div>{profile.bio&&<p className="mt-5 text-sm leading-6">{profile.bio}</p>}<div className="mt-3 flex flex-wrap gap-3 text-xs text-muted">{profile.primary_goal&&<span>{profile.primary_goal}</span>}{profile.experience_level&&<span>· {profile.experience_level}</span>}{profile.location&&<span className="flex items-center gap-1"><MapPin size={13}/>{profile.location}</span>}{profile.website&&<a className="text-aqua" href={profile.website} rel="noreferrer" target="_blank">{profile.website}</a>}</div>{profile.profile_song_url&&profile.profile_song_title&&<ProfileSong url={profile.profile_song_url} title={profile.profile_song_title} artist={profile.profile_song_artist} artwork={profile.profile_song_artwork_url}/>}<div className="mt-5 flex gap-3">{own?<a href="/settings/profile" className="flex-1 rounded-full border border-white/10 py-2 text-center text-sm font-semibold">Edit profile</a>:<><FollowButton status={status} onClick={follow}/><button disabled className="flex-1 rounded-full border border-white/10 py-2 text-sm text-muted">Message · Soon</button></>}</div></header>}
