"use client";
import { useState } from "react";
import { ArrowRight, BedDouble, Check, Dumbbell, Droplets, Flame, Plus, Scale, Sparkles, Timer, Utensils } from "lucide-react";
import AppShell from "./app-shell";
import { Button, Metric, Progress } from "./ui";

export default function Today({welcome=false,firstName="",setupLater=false,dashboardConfig}:{welcome?:boolean;firstName?:string;setupLater?:boolean;dashboardConfig?:{show_training?:boolean;show_nutrition?:boolean;nutrition_setup_incomplete?:boolean}}){
 const [adapt,setAdapt]=useState(false); const [done,setDone]=useState(false);
 return <AppShell><div className="flex flex-col gap-7">
  {welcome&&<section className="card border-acid/30 bg-acid/[.06] p-6"><p className="eyebrow">Your starting point is ready</p><h1 className="mt-2 text-3xl font-semibold">Welcome to PSFIT{firstName?`, ${firstName}`:""}.</h1><p className="mt-2 text-muted">{setupLater?"Explore PSFIT now and build your personalized plan whenever you are ready.":"Your personalized plan is ready."}</p><div className="mt-5 flex flex-wrap gap-3">{dashboardConfig?.show_training&&<Button href="/workouts">View my workout plan</Button>}{dashboardConfig?.show_nutrition&&<Button variant="quiet" href="/nutrition">View nutrition guidance</Button>}</div></section>}
  {setupLater&&<section className="card flex flex-col justify-between gap-4 border-aqua/20 p-6 sm:flex-row sm:items-center"><div><h2 className="text-xl font-semibold">Build your personalized plan</h2><p className="mt-1 text-sm text-muted">Answer a few questions when you are ready.</p></div><Button href="/onboarding/personalization?edit=true">Start setup</Button></section>}
  {dashboardConfig?.nutrition_setup_incomplete&&<section className="card border-aqua/20 p-5"><h2 className="font-semibold">Complete your body information to estimate nutrition targets.</h2><p className="mt-2 text-sm text-muted">Your available PSFIT features are ready; nutrition estimates can be completed later.</p></section>}
  <div className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><p className="eyebrow">Monday · Today</p><h1 className="mt-2 text-4xl font-semibold tracking-tight">Good morning.</h1><p className="mt-2 text-muted">Your best next step is ready.</p></div><button onClick={()=>setAdapt(!adapt)} className="flex items-center gap-2 self-start rounded-full bg-acid px-5 py-3 text-sm font-bold text-ink"><Sparkles size={16}/>Real-Life Mode</button></div>
  {adapt&&<div className="card border-acid/30 p-5"><p className="font-semibold">What changed today?</p><div className="mt-4 flex flex-wrap gap-2">{["Only 20 minutes","Low energy","No gym access","Muscle soreness","Only dumbbells","Cannot jump"].map(x=><button key={x} onClick={()=>setAdapt(false)} className="rounded-full border border-white/10 px-3 py-2 text-xs hover:border-acid hover:text-acid">{x}</button>)}</div></div>}
  <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric label="Daily readiness" value="82" sub="Ready for planned intensity"/><Metric label="Momentum" value="84" sub="Strong across the last 30 days" color="aqua"/><Metric label="Sleep" value="7h 34m" sub="28m above weekly average"/><Metric label="Recovery" value="Good" sub="No limiting signals" color="aqua"/></div>
  <div className="grid gap-5 xl:grid-cols-[1.4fr_.8fr]">
   <section className="card p-6"><div className="flex justify-between"><div><p className="text-sm text-muted">Today’s workout</p><h2 className="mt-2 text-2xl font-semibold">Upper body strength</h2></div><div className="grid h-12 w-12 place-items-center rounded-2xl bg-acid/10"><Dumbbell className="text-acid"/></div></div><div className="mt-8 grid grid-cols-3 gap-3 text-sm"><div><p className="text-muted">Duration</p><p className="mt-1">42 min</p></div><div><p className="text-muted">Exercises</p><p className="mt-1">6 movements</p></div><div><p className="text-muted">Focus</p><p className="mt-1">Push · Pull</p></div></div><div className="mt-8 flex flex-wrap gap-3"><Button href="/workouts/session/today">Start workout <ArrowRight size={16}/></Button><Button variant="quiet" href="/workouts/today">View details</Button></div></section>
   <section className="card bg-acid p-6 text-ink"><p className="text-xs font-bold uppercase tracking-widest">Minimum Win</p><h2 className="mt-5 text-2xl font-semibold">Keep the signal alive.</h2><p className="mt-3 text-sm leading-6 opacity-70">Short on time? Complete 3 compound movements in 12 minutes. It still supports today’s consistency.</p><button onClick={()=>setDone(true)} className="mt-7 flex items-center gap-2 rounded-full bg-ink px-4 py-2.5 text-sm font-bold text-paper">{done?<><Check size={16}/>Minimum Win saved</>:<><Timer size={16}/>Use 12-minute version</>}</button></section>
  </div>
  <div className="grid gap-5 lg:grid-cols-3">
   <section className="card p-6 lg:col-span-2"><div className="flex items-center justify-between"><div><p className="text-sm text-muted">Nutrition progress</p><h2 className="mt-1 text-xl font-semibold">Fuel the rest of your day</h2></div><Utensils className="text-acid"/></div><div className="mt-8 grid gap-6 sm:grid-cols-3"><Mini label="Calories" value="1,420 / 2,180" pct={65}/><Mini label="Protein" value="112 / 146g" pct={77}/><Mini label="Hydration" value="1.8 / 2.8L" pct={64}/></div><div className="mt-7 flex gap-3"><Button variant="quiet" href="/meals"><Plus size={16}/>Quick log meal</Button></div></section>
   <section className="card p-6"><p className="text-sm text-muted">PSFIT Twin insight</p><Sparkles className="mt-6 text-aqua"/><p className="mt-4 font-semibold">Your sleep consistency is supporting this week’s training quality.</p><p className="mt-3 text-sm leading-6 text-muted">Maintaining the current range may keep your optimized scenario on track.</p><a href="/twin" className="mt-5 inline-block text-sm font-semibold text-aqua">Explore scenarios →</a></section>
  </div>
  <div className="grid gap-4 sm:grid-cols-3"><Action icon={Scale} title="Log weight" href="/progress"/><Action icon={Droplets} title="Add water" href="/nutrition"/><Action icon={Flame} title="Weekly activity" href="/momentum"/></div>
 </div></AppShell>
}
function Mini({label,value,pct}:{label:string;value:string;pct:number}){return <div><div className="mb-3 flex justify-between text-sm"><span className="text-muted">{label}</span><span>{value}</span></div><Progress value={pct}/></div>}
function Action({icon:Icon,title,href}:{icon:typeof Scale;title:string;href:string}){return <a href={href} className="card flex items-center justify-between p-5 transition hover:border-white/20"><span className="flex items-center gap-3"><Icon size={19} className="text-acid"/>{title}</span><ArrowRight size={16}/></a>}
