"use client";
import { Check,CircleX } from "lucide-react";
import { PsfitLoader } from "@/components/ui/psfit-loader";
import { useRouter } from "next/navigation";
import { useEffect,useRef,useState } from "react";
type Status="pending"|"running"|"completed"|"failed";
const stages=["Entendendo seus objetivos","Organizando sua semana de treino","Equilibrando o volume de treino","Estimando suas metas nutricionais","Preparando sua primeira semana"];
const stepIndex:Record<string,number>={authentication:0,profile:0,preferences:0,workout:2,nutrition:3,finalizing:4};
export function GeneratingPlan(){const router=useRouter();const hasStartedRef=useRef(false);const inFlightRef=useRef(false);const [statuses,setStatuses]=useState<Status[]>(["pending","pending","pending","pending","pending"]);const [error,setError]=useState("");async function generate(){if(inFlightRef.current)return;inFlightRef.current=true;setError("");setStatuses(["running","pending","pending","pending","pending"]);try{const response=await fetch("/api/onboarding/generate",{method:"POST"});const result=await response.json() as {ok?:boolean;next?:string;step?:string;error?:string};if(!response.ok||!result.ok){const failed=stepIndex[result.step??"finalizing"]??4;setStatuses(stages.map((_,index)=>index<failed?"completed":index===failed?"failed":"pending"));setError(result.error??"Não foi possível gerar seu plano.");return}setStatuses(stages.map(()=>"completed"));router.replace(result.next??"/dashboard?welcome=true");router.refresh()}catch{setStatuses(["failed","pending","pending","pending","pending"]);setError("Não foi possível gerar seu plano.")}finally{inFlightRef.current=false}}useEffect(()=>{if(hasStartedRef.current)return;hasStartedRef.current=true;void generate()},[]);function retry(){if(inFlightRef.current)return;hasStartedRef.current=true;void generate()}return <div className="space-y-3">{stages.map((stage,index)=><div key={stage} className={`flex items-center gap-3 rounded-xl border p-4 ${statuses[index]==="failed"?"border-red-400/30 bg-red-400/[.05]":"border-white/[.08] bg-[#090c0a]"}`}><StatusIcon status={statuses[index]}/><span className="text-sm">{stage}</span></div>)}{error&&<div className="mt-5"><p role="alert" className="text-sm text-red-400">{error}</p><button type="button" onClick={retry} disabled={inFlightRef.current} className="mt-3 rounded-full bg-acid px-5 py-2 text-sm font-bold text-ink disabled:opacity-50">Tentar novamente</button></div>}</div>}
function StatusIcon({status}:{status:Status}){if(status==="running")return <PsfitLoader size="sm" label=""/>;if(status==="completed")return <Check className="text-aqua" size={18}/>;if(status==="failed")return <CircleX className="text-red-400" size={18}/>;return <span className="h-[18px] w-[18px] rounded-full border border-white/15"/>}
